evento:
  nombre: "Romería 2026"

calendario:
  Viernes:
    "Mediodía": "eleccion"
    "Cena" : "eleccion"
  Sábado:
    "Mediodía": "fijo"
    "Cena": "eleccion"
  Domingo:
    "Mediodía": "fijo"

menu_comida:
  # Formato -> "Nombre": [multiplicador_solo, multiplicador_acompañado]
  "Hamburguesas": [2, 1]
  "Filetes de pollo": [4, 2]
  "Filetes de lomo": [4, 3]
  "Panceta": [2, 2]
  "Chorizo de pollo": [0.5, 0.5]
  "Morcilla": [0.5, 0.5]
  "Pinchos de pollo": [0.1, 0.1]

menu_bebida:
  alcohol: ["NADA", "RED LABEL", "DYC 8", "BALLANTINES", "BEEFEATER", "BRUGAL", "RON BARCELÓ", "PUERTO DE INDIAS", "LARIOS"]
  refrescos: ["NADA", "COCA COLA ZERO", "COCA COLA", "FANTA LIMON", "FANTA NARANJA", "7UP", "FUZZE TEA MARACUYÁ", "TÓNICA", "AGUA CON GAS"]
  extras: ["Cerveza", "Tinto/Calimocho", "Rebujito", "Martini Blanco"]
  chupitos_opciones: ["JAGGER", "TEQUIFRESA", "MELONCHELO", "CREMA DE ORUJO", "TEQUILA"]

menu_embutido:
  "Jamón": 8.00
  "Embutido variado": 8.00

ratios_embutido:
  personas_por_plato: 6

ratios_bebida:
  alcohol_por_persona: 1.25
  cerveza_diaria: 8
  pack_cerveza: 24 #unidades por caja
  tinto_por_persona: 1.25
  refresco_por_dia: 1.75
  cubos_rebujito_diarios: 2
  botellas_manzanilla_por_cubo: 1 # Asumimos 1 botella por cubo, si es diferente lo cambiamos
  martini_por_persona: 0.20
  dyc_extra_por_manzanilla: 0.25
  chupito_por_persona: 0.15

precios_bebida:
  "RED LABEL": 13.10
  "DYC 8": 12.22
  "BALLANTINES": 13.18
  "BEEFEATER": 13.91
  "BRUGAL": 13.55 # Asumiendo precio similar a Ron Barceló
  "RON BARCELÓ": 15.24
  "PUERTO DE INDIAS": 15.00
  "LARIOS": 11.60
  "CAJAS CERVEZA (24 uds)": 9.50
  "TINTO": 2.5
  "MANZANILLA": 6.66
  "MARTINI BLANCO": 9.44
  "COCA COLA ZERO": 1.65
  "COCA COLA": 1.65
  "FANTA LIMON": 1.40
  "FANTA NARANJA": 1.40
  "AGUA": 0.8 # Asumiendo garrafa 5L
  "7UP": 1.40
  "FUZZE TEA MARACUYÁ": 1.5
  "TÓNICA": 1.1
  "AGUA CON GAS": 2.00
  "JAGGER": 13.25
  "TEQUIFRESA": 12.90
  "MELONCHELO": 7.87
  "CREMA DE ORUJO": 12.22
  "TEQUILA": 15.25

precios_comida:
  "Hamburguesas": 0.72        # €/unidad
  "Morcilla": 2.35            # €/unidad
  "Panceta": 0.55             # €/unidad
  "Pinchos de pollo": 3.50    # €/tarrina 0.5 kg
  "Filetes de pollo": 0.58    # €/unidad
  "Chorizo de pollo": 0.68    # €/unidad
  "Filetes de lomo": 0.40     # €/unidad
  "Solomillos": 7.30          # €/unidad (aprox)
  "Pollo paella (kg)": 6.70   # €/kg
  "Magro paella (kg)": 6.75   # €/kg
  "Barras de pan": 0.85
  "Bandeja dulces pequeña": 4.50
  "Medio pan": 1.20
  "Empanadas": 30.00
  "Gambas (kg)": 23.00
  "Langostinos (kg)": 13.80
  "Gambones (€/ud)": 0.69   #El kg es 13.8€ y asumimos que 1 ud pesa 50g => 13.8€/kg / 20 ud/kg = 0.69€/ud
  "Menestra marisco (kg)": 8.00

ratios_paella:
  kg_por_persona_pollo: 0.0536  # = 1.5 kg / 28 personas (referencia 2025)
  kg_por_persona_magro: 0.0536  # = 1.5 kg / 28 personas (referencia 2025)


ratios_pescado:
  # Kilos por persona. Ponemos 0 de momento hasta que sepas las cantidades.
  kg_por_persona_gambas: 0.15
  ud_por_persona_gambones: 1
  kg_por_persona_langostinos: 0.15
  kg_por_persona_menestra_marisco: 0.1

ratios_panaderia:
  empanadas_fijas: 3  # Total fijo independientemente de personas/días

ratios_solomillos:
  personas_por_solomillo: 2  # 1 solomillo por cada 2 personas

cuotas:
  normal: 130
  sin_alcohol: 110

gastos_fijos:
  alquiler_furgon: 180.0
  fianza_furgon: 150.0  # Ojo, esto se devuelve, pero hay que recaudarlo ahora
  equipo_musica: 400.0
  licencia_luz: 50.0
  estimacion_hielo: 150.0